### ISSUE TITLE
Master branch difficult to bootstrap

### ISSUE THREAD

**Issue by schrepfler** [denisrosset/alasc#13]
Hi, not sure if I'm doing something wrong but I don't think the dependencies (I think qalg and/or metal) are not published anywhere, and themselves are not stable/building. What can be done to have a stable base core? Are we waiting for something upstream (Cats)?

**Comment by denisrosset** [comment]
Hi @schrepfler,

I wrote alasc during my PhD thesis on quantum information, and it just went through a major refactoring. I'm now happy to release something.

During the last week, I was trying to understand how to release to bintray, and got it to work for a small project. I'm now releasing the `scala-metal` dependency; once this is done, I will do a formal release of `alasc`.

And then begins the formidable task of having good documentation for `alasc`, setting up Github pages and so on.

I'm quite happy how using Scala to study group theory turned out. Hope you will be able to share the excitement soon!

Denis

**Comment by denisrosset** [comment]
@schrepfler, I've made another refactoring.

Now, the interface should be much more user friendly. Thus, closing this PR.
